### PR TITLE
 encode: fix response corruption when handle_errors is used

### LINKED ISSUE #6617: [encode] Encoding bug when handle_errors is invoked
The HTTP response body is corrupted due to an encoding bug, which occurs when combining `encode` and `handle_errors` directives, especially with `file_server` and `templates`.

### What We Expect

Caddy will use the HTTP response from `handle_errors` to determine how to encode the response and send appropriate headers (i.e. `Content-Encoding`).

### What Happens

**EDIT:** ~~Caddy will start compressing the payload and send `Content-Encoding` headers; however,~~
When an error occurs and the HTTP response is set by the `handle_errors` directive, the response body somehow gets corrupted. I believe this is the case even for buffered HTTP responses.

### To reproduce

- `encode` directive is used to enable encoding. It does not matter which encoding format is used.
- the client sends appropriate `Accept-Encoding` headers to enable the encoding middleware
- the `file_server` directive serves a file larger than the [`minimumLength` for the encode directive](https://caddyserver.com/docs/caddyfile/directives/encode#minimum_length)
- there was some sort of error that occurs during the request that causes the `handle_errors` directive to be invoked

### Example:

Consider this Caddyfile configuration:

```caddyfile
example.com {
	encode zstd gzip
	handle_errors {
		respond "Error"
	}
	root * /var/www/example.com
	templates
	file_server
}
```

Suppose file `/var/www/example.com/test.html` is greater than 512 bytes and contains a template error of some kind. In this case, Caddy is supposed to respond with "Error" but instead delivers a corrupted HTTP response. In the above example, the HTTP gzip-encoded response body looks like this (encoded in hexadecimal):

```hex
1f8b 0800 0009 6e88 00ff 0300 0000 0000 0000 0000 4572 726f 72
```

Notice the last 5 bytes are the string "Error" but the first bytes appear to be a valid gzip encoding of 0 bytes.

I am happy to write a PR for this if I can get some pointers on where to look.

### PR DESCRIPTION
**Pull request by Siomachkin**
Fixes response corruption when encode and handle_errors directives are used together - Adds disabled flag to responseWriter to prevent encoding during error processing - Resolves issue where gzip headers were mixed with plain text error responses.

Fixes #6617

**Test Results**
Before Fix (Corrupted Response)
```
curl -k -H "Accept-Encoding: gzip" https://localhost:8080/  
# Result: Mixed gzip headers with plain text, corrupted response  
# Headers contained Content-Encoding: gzip but body was partially compressed  
```

After Fix (Clean Error Response)
```
curl -k -H "Accept-Encoding: gzip" https://localhost:8080/  
# Result: Clean error response  
# HTTP/1.1 500 Internal Server Error  
# No Content-Encoding header (encoding disabled)  
# Body: "Error: Status 500" (plain text, readable)  
```

Normal Responses Still Work
```
curl -k -H "Accept-Encoding: gzip" https://localhost:8080/valid.html  
# Result: Properly compressed  
# HTTP/1.1 200 OK  
# Content-Encoding: gzip  
# Body: Compressed content
```  

Test Configuration Used
```
localhost:8080 {
    encode zstd gzip
    handle_errors {
        respond "Error: Status {http.error.status_code}"
    }
    root * .
    templates
    file_server
}
```

Template file with error: {{ poop }} (undefined variable)

**Assistance Disclosure**
I consulted Claude to understand the project architecture, but I authored/coded the fix myself.

### CODE REVIEW

**Review by mholt — APPROVED** [review]
Ah wow, thank you for the fix! This looks good to me.

**Comment by mholt** [comment]
Oh, just make sure to run gofmt to appease the linter :) -- and be sure to sign the CLA.

File: modules/caddyhttp/encode/encode.go [hunk 1]
```diff
@@ -426,6 +438,13 @@ func (rw *responseWriter) Unwrap() http.ResponseWriter {
 // init should be called before we write a response, if rw.buf has contents.
 func (rw *responseWriter) init() {
 	hdr := rw.Header()
+
+	// Don't initialize encoder for error responses
+	// This prevents response corruption when handle_errors is used
+	if rw.disabled {
+		return
+	}
```
Comment (francislavoie) [inline modules/caddyhttp/encode/encode.go:443]: I think this should be moved above `hdr :=`, I don't see a reason it needs to be after it.

**Review by francislavoie — APPROVED** [review]
