### PR TITLE
caddyauth: Add singleflight for basic auth

### LINKED ISSUE #5338: Basic Auth causes Caddy to use an extraordinary amount of CPU while viewing the NetData Dashboard
### 1a. Operating system and version

```
Ubuntu 22.04, but both caddy and netdata are running using docker compose.
```

### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.6.2 h1:wKoFIxpmOJLGl3QXoo6PNbYvGW4xLEgo32GPBEjWL8o=
```

## 2. Description

This is same issue as an old one https://github.com/caddyserver/caddy/issues/4267

### 2a. What happens (briefly explain what is wrong)

Here is what happens on caddy container restart with basic auth enabled:
изображение
And here is same 1-minute window with caddy restart without basic auth:
изображение

### 2b. Why it's a bug (if it's not obvious)

Too high CPU usage.

### 2c. Log output

Looks like this 15-sec long high CPU load happens because of just 18 requests sent by netdata (IP/DOMAIN redacted):
```
{"level":"info","ts":1674856181.5576816,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
{"level":"warn","ts":1674856181.564568,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
2023/01/27 21:49:41.590	INFO	admin	admin endpoint started	{"address": "localhost:2019", "enforce_origin": false, "origins": ["//localhost:2019", "//[::1]:2019", "//127.0.0.1:2019"]}
2023/01/27 21:49:41.593	INFO	http	server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS	{"server_name": "srv0", "https_port": 443}
2023/01/27 21:49:41.594	INFO	http	enabling automatic HTTP->HTTPS redirects	{"server_name": "srv0"}
2023/01/27 21:49:41.605	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0xc000439340"}
2023/01/27 21:49:41.610	INFO	http	enabling HTTP/3 listener	{"addr": ":443"}
{"level":"info","ts":1674856181.6112509,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details."}
2023/01/27 21:49:41.613	INFO	http.log	server running	{"name": "srv0", "protocols": ["h1", "h2", "h3"]}
2023/01/27 21:49:41.613	INFO	http.log	server running	{"name": "remaining_auto_https_redirects", "protocols": ["h1", "h2", "h3"]}
2023/01/27 21:49:41.613	INFO	http	enabling automatic TLS certificate management	{"domains": ["etesync.DOMAIN.TLD", "netdata.primary.DOMAIN.TLD"]}
2023/01/27 21:49:41.620	INFO	autosaved config (load with --resume flag)	{"file": "/config/caddy/autosave.json"}
2023/01/27 21:49:41.620	INFO	serving initial configuration
2023/01/27 21:49:41.620	INFO	tls	cleaning storage unit	{"description": "FileStorage:/data/caddy"}
2023/01/27 21:49:41.629	INFO	tls	finished cleaning storage units
2023/01/27 21:50:25.616	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.cpu&_=1674856210484&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300"}, "user_id": "powerman", "duration": 14.857551031, "size": 0, "status": 0}
2023/01/27 21:50:25.633	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.cpu&_=1674856210427&format=json&points=262&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-300"}, "user_id": "powerman", "duration": 14.992071428, "size": 0, "status": 0}
2023/01/27 21:50:25.633	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.ram&_=1674856210451&format=array&points=300&group=average&gtime=0&options=absolute%7Cpercentage%7Cjsonwrap%7Cnonzero&after=-300&dimensions=used%7Cbuffers%7Cactive%7Cwired"}, "user_id": "powerman", "duration": 14.983164857, "size": 0, "status": 0}
2023/01/27 21:50:25.635	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.net&_=1674856210477&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300&dimensions=received"}, "user_id": "powerman", "duration": 14.917745559, "size": 0, "status": 0}
2023/01/27 21:50:25.661	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.io&_=1674856210461&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300&dimensions=in"}, "user_id": "powerman", "duration": 14.996486785, "size": 0, "status": 0}
2023/01/27 21:50:25.662	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.net&_=1674856210467&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300&dimensions=sent"}, "user_id": "powerman", "duration": 14.96954706, "size": 0, "status": 0}
2023/01/27 21:50:25.663	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.cpu&_=1674856210494&format=json&points=111&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-300&dimensions=iowait"}, "user_id": "powerman", "duration": 14.725561648, "size": 0, "status": 0}
2023/01/27 21:50:25.669	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.io&_=1674856210505&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300&dimensions=out"}, "user_id": "powerman", "duration": 14.711465941, "size": 0, "status": 0}
2023/01/27 21:50:25.669	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.cpu&_=1674856210506&format=json&points=111&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-300&dimensions=softirq"}, "user_id": "powerman", "duration": 14.862092634, "size": 0, "status": 0}
2023/01/27 21:50:25.676	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.net&_=1674856225496&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300&dimensions=received"}, "user_id": "powerman", "duration": 0.042953096, "size": 1887, "status": 200}
2023/01/27 21:50:25.678	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.net&_=1674856225495&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300&dimensions=sent"}, "user_id": "powerman", "duration": 0.04421093, "size": 1887, "status": 200}
2023/01/27 21:50:25.681	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.cpu&_=1674856225440&format=json&points=262&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-300"}, "user_id": "powerman", "duration": 0.047251259, "size": 3653, "status": 200}
2023/01/27 21:50:25.681	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.ram&_=1674856225459&format=array&points=300&group=average&gtime=0&options=absolute%7Cpercentage%7Cjsonwrap%7Cnonzero&after=-300&dimensions=used%7Cbuffers%7Cactive%7Cwired"}, "user_id": "powerman", "duration": 0.047498366, "size": 1473, "status": 200}
2023/01/27 21:50:25.681	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.io&_=1674856225535&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300&dimensions=out"}, "user_id": "powerman", "duration": 0.015849202, "size": 1522, "status": 200}
2023/01/27 21:50:25.681	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.cpu&_=1674856225539&format=json&points=111&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-300&dimensions=softirq"}, "user_id": "powerman", "duration": 0.018101394, "size": 927, "status": 200}
2023/01/27 21:50:25.682	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.io&_=1674856225473&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300&dimensions=in"}, "user_id": "powerman", "duration": 0.048085624, "size": 1295, "status": 200}
2023/01/27 21:50:25.682	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.cpu&_=1674856225517&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300"}, "user_id": "powerman", "duration": 0.016747384, "size": 1286, "status": 200}
2023/01/27 21:50:25.682	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.cpu&_=1674856225518&format=json&points=111&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-300&dimensions=iowait"}, "user_id": "powerman", "duration": 0.016788965, "size": 929, "status": 200}
2023/01/27 21:50:31.924	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.net&_=1674856231812&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300&dimensions=sent"}, "user_id": "powerman", "duration": 0.005819312, "size": 1887, "status": 200}
2023/01/27 21:50:31.928	INFO	http.log.access	handled request	{"request": {"remote_ip": "1.2.3.4", "proto": "HTTP/3.0", "method": "GET", "host": "netdata.primary.DOMAIN.TLD", "uri": "/api/v1/data?chart=system.net&_=1674856231811&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300&dimensions=received"}, "user_id": "powerman", "duration": 0.009109117, "size": 1884, "status": 200}
```

### 2d. Workaround(s)

Disabling basic auth is not a viable option, so…

I think it should be fixed by caddy avoiding hashing same password in more than one goroutine at same time.

## 3. Tutorial (minimal steps to reproduce the bug)

Caddyfile used in docker image `caddy:2.6.2`:
```
{
    email powerman@DOMAIN.TLD
    log default {
        format filter {
            wrap console
            fields {
                request>headers delete
                request>remote_port delete
                request>tls delete
                resp_headers delete
            }
        }
    }
}

netdata.primary.DOMAIN.TLD {
    basicauth {
        powerman HASH
    }

    reverse_proxy netdata:19999

    log
}
```

### PR DESCRIPTION
**Pull request by u5surf**
* Fixes #5338
* it occurred the thunder herd problem like this https://medium.com/@mhrlife/avoid-duplicate-requests-while-filling-cache-98c687879f59

### CODE REVIEW

File: modules/caddyhttp/caddyauth/basicauth.go [hunk 1]
```diff
@@ -190,12 +192,15 @@ func (hba HTTPBasicAuth) correctPassword(account Account, plaintextPassword []by
 	if ok {
 		return same, nil
 	}
-
 	// slow track: do the expensive op, then add it to the cache
-	same, err := compare()
+	// but it occurred the thunder herd, thus it uses singleflight
```
Comment (francislavoie) [inline modules/caddyhttp/caddyauth/basicauth.go:196]:
```suggestion
    // slow track: do the expensive op, then add it to the cache
	// but perform it in a singleflight group so that multiple
	// parallel requests using the same password don't cause a
	// thundering herd problem by all performing the same hashing
	// operation before the first one finishes and caches it.
```

**Comment by francislavoie** [comment]
Oooh, that's really cool! I didn't know Go had a build-in package to deal with this particular problem.

File: modules/caddyhttp/caddyauth/basicauth.go [hunk 2]
```diff
@@ -190,12 +192,19 @@ func (hba HTTPBasicAuth) correctPassword(account Account, plaintextPassword []by
 	if ok {
 		return same, nil
 	}
-
 	// slow track: do the expensive op, then add it to the cache
-	same, err := compare()
+    // slow track: do the expensive op, then add it to the cache
```
Comment (francislavoie) [inline modules/caddyhttp/caddyauth/basicauth.go:196]: Oh whoops, my bad. I left in this line by accident when I was typing the suggestion

```suggestion
```

**Review by mholt — APPROVED** [review]
I also learned something new -- thanks for the patch! I might have to use this in CertMagic. I looked at the source for singleflight and it's doing basically the same thing as I hand-rolled in CertMagic.

**Comment by mholt** [comment]
I'm not sure why the lint keeps failing on this one.
