### PR TITLE
fix OOM issue caught by fuzzing

### LINKED ISSUE #2851: [FUZZIT] Crash at fuzzing target parse-network-address
A new crash was discovered for fuzzing target parse-network-address.
Here is a snippet of the log:
```
S: 1 CrossOver-
FUZZER: #1712	REDUCE ft: 875 corp: 72/783b lim: 4 exec/s: 0 rss: 66Mb L: 2/20 MS: 2 CopyPart-EraseBytes-
FUZZER: #1749	NEW    ft: 877 corp: 73/801b lim: 4 exec/s: 1749 rss: 66Mb L: 18/20 MS: 2 CopyPart-CrossOver-
FUZZER: #1780	REDUCE ft: 877 corp: 73/797b lim: 4 exec/s: 1780 rss: 66Mb L: 4/20 MS: 1 EraseBytes-
FUZZER: #1832	REDUCE ft: 878 corp: 74/805b lim: 4 exec/s: 1832 rss: 66Mb L: 8/20 MS: 2 PersAutoDict-CopyPart- DE: "\xff\xff"-
FUZZER: #1854	REDUCE ft: 878 corp: 74/803b lim: 4 exec/s: 1854 rss: 66Mb L: 6/20 MS: 2 ShuffleBytes-EraseBytes-
FUZZER: #1879	REDUCE ft: 878 corp: 74/802b lim: 4 exec/s: 1879 rss: 66Mb L: 6/20 MS: 5 ChangeBinInt-ChangeBit-EraseBytes-ChangeBit-ChangeBinInt-
FUZZER: #1970	REDUCE ft: 878 corp: 74/801b lim: 4 exec/s: 1970 rss: 66Mb L: 9/20 MS: 1 EraseBytes-
FUZZER: #2036	NEW    ft: 881 corp: 75/820b lim: 4 exec/s: 2036 rss: 66Mb L: 19/20 MS: 1 CopyPart-
FUZZER: #2097	NEW    ft: 882 corp: 76/837b lim: 4 exec/s: 349 rss: 454Mb L: 17/20 MS: 1 ShuffleBytes-
FUZZER: #2103	REDUCE ft: 882 corp: 76/834b lim: 4 exec/s: 350 rss: 454Mb L: 6/20 MS: 1 EraseBytes-
FUZZER: #2118	REDUCE ft: 882 corp: 76/833b lim: 4 exec/s: 353 rss: 454Mb L: 10/20 MS: 5 ChangeBit-ChangeBit-ChangeByte-ShuffleBytes-EraseBytes-
FUZZER: #2139	REDUCE ft: 882 corp: 76/831b lim: 4 exec/s: 356 rss: 454Mb L: 10/20 MS: 1 EraseBytes-
FUZZER: #2320	REDUCE ft: 882 corp: 76/830b lim: 4 exec/s: 154 rss: 573Mb L: 15/20 MS: 1 CrossOver-
FUZZER: #2342	REDUCE ft: 882 corp: 76/829b lim: 4 exec/s: 156 rss: 573Mb L: 10/20 MS: 2 ChangeBinInt-EraseBytes-
FUZZER: #2393	REDUCE ft: 882 corp: 76/828b lim: 4 exec/s: 159 rss: 573Mb L: 2/20 MS: 1 CrossOver-
FUZZER: #2394	REDUCE ft: 882 corp: 76/827b lim: 4 exec/s: 159 rss: 573Mb L: 2/20 MS: 1 EraseBytes-
FUZZER: #2397	REDUCE ft: 890 corp: 77/840b lim: 4 exec/s: 159 rss: 573Mb L: 13/20 MS: 3 ShuffleBytes-ChangeByte-ChangeBit-
FUZZER: #2424	NEW    ft: 891 corp: 78/857b lim: 4 exec/s: 96 rss: 649Mb L: 17/20 MS: 2 ChangeByte-PersAutoDict- DE: "\xff\xff"-
FUZZER: #2485	REDUCE ft: 891 corp: 78/855b lim: 4 exec/s: 99 rss: 649Mb L: 4/20 MS: 1 EraseBytes-
FUZZER: #2491	NEW    ft: 892 corp: 79/872b lim: 4 exec/s: 83 rss: 649Mb L: 17/20 MS: 1 ChangeASCIIInt-
FUZZER: #2557	REDUCE ft: 892 corp: 79/871b lim: 4 exec/s: 73 rss: 670Mb L: 12/20 MS: 1 EraseBytes-
FUZZER: #2568	NEW    ft: 893 corp: 80/879b lim: 4 exec/s: 73 rss: 670Mb L: 8/20 MS: 1 CopyPart-
FUZZER: #2570	REDUCE ft: 893 corp: 80/877b lim: 4 exec/s: 73 rss: 670Mb L: 4/20 MS: 2 CopyPart-EraseBytes-
FUZZER: #2677	NEW    ft: 894 corp: 81/894b lim: 4 exec/s: 58 rss: 755Mb L: 17/20 MS: 2 ChangeBit-ShuffleBytes-
FUZZER: #2684	NEW    ft: 895 corp: 82/902b lim: 4 exec/s: 58 rss: 755Mb L: 8/20 MS: 2 ShuffleBytes-ShuffleBytes-
FUZZER: #2695	REDUCE ft: 895 corp: 82/901b lim: 4 exec/s: 58 rss: 755Mb L: 12/20 MS: 1 EraseBytes-
FUZZER: #2844	NEW    ft: 898 corp: 83/919b lim: 4 exec/s: 45 rss: 755Mb L: 18/20 MS: 4 ShuffleBytes-ShuffleBytes-ChangeBit-PersAutoDict- DE: "\x00\x00\x00\x00\x00\x00\x00\x00"-
FUZZER: #2850	REDUCE ft: 898 corp: 83/916b lim: 4 exec/s: 45 rss: 755Mb L: 10/20 MS: 1 CrossOver-
FUZZER: #2909	REDUCE ft: 898 corp: 83/914b lim: 4 exec/s: 39 rss: 755Mb L: 4/20 MS: 4 ChangeByte-ChangeBinInt-ChangeByte-EraseBytes-
FUZZER: #2941	REDUCE ft: 898 corp: 83/910b lim: 4 exec/s: 40 rss: 755Mb L: 4/20 MS: 2 CopyPart-EraseBytes-
FUZZER: #3104	REDUCE ft: 899 corp: 84/914b lim: 4 exec/s: 30 rss: 755Mb L: 4/20 MS: 3 ShuffleBytes-ChangeByte-ShuffleBytes-
FUZZER: #3189	REDUCE ft: 899 corp: 84/911b lim: 4 exec/s: 26 rss: 756Mb L: 3/20 MS: 5 ChangeBinInt-ChangeBit-ChangeBit-CopyPart-CrossOver-
FUZZER: #3285	NEW    ft: 960 corp: 85/928b lim: 4 exec/s: 26 rss: 773Mb L: 17/20 MS: 1 ShuffleBytes-
FUZZER: #3511	NEW    ft: 1020 corp: 86/945b lim: 4 exec/s: 27 rss: 773Mb L: 17/20 MS: 1 ChangeASCIIInt-
FUZZER: #3596	NEW    ft: 1022 corp: 87/963b lim: 4 exec/s: 25 rss: 773Mb L: 18/20 MS: 5 PersAutoDict-ChangeBit-ChangeByte-ChangeByte-CrossOver- DE: "\x01\x00"-
FUZZER: #3636	NEW    ft: 1025 corp: 88/976b lim: 4 exec/s: 25 rss: 773Mb L: 13/20 MS: 5 EraseBytes-EraseBytes-ChangeBit-ChangeByte-InsertByte-
FUZZER: ==23== ERROR: libFuzzer: out-of-memory (used: 1985Mb; limit: 1984Mb)
FUZZER:    To change the out-of-memory limit use -rss_limit_mb=<N>
FUZZER: 
FUZZER: MS: 2 ChangeASCIIInt-CopyPart-; base unit: fe75feba60d9f051d75977c81fd564e0c76bb2ba
FUZZER: 0x6c,0xff,0xff,0x21,0x3a,0x37,0x2d,0x36,0x34,0x32,0x36,0x34,0x32,0x33,0x37,0x37,0x30,
FUZZER: l\xff\xff!:7-6426423770
FUZZER: artifact_prefix='./'; Test unit written to ./artifact
FUZZER: Base64: bP//ITo3LTY0MjY0MjM3NzA=
FUZZER: SUMMARY: libFuzzer: out-of-memory
FUZZER: stat::number_of_executed_units: 3733
FUZZER: stat::average_exec_per_sec:     22
FUZZER: stat::new_units_added:          153
FUZZER: stat::slowest_unit_time_sec:    0
FUZZER: stat::peak_rss_mb:              1987
2019/11/01 06:29:18 process finished with error = exit status 76
2019/11/01 06:29:18 Exit Status: 76
2019/11/01 06:29:18 uploading crash...

```

More details can be found [here](https://app.fuzzit.dev/orgs/caddyserver-gh/targets/parse-network-address/M7BeFDA98jYqNiFpMQYU)

Cheers,
Fuzzit Bot

### PR DESCRIPTION
**Pull request by Mohammed90**
## 1. What does this change do, exactly?

Changes the return of `ParseNetworkAddress` to be an instance of new struct type `Listener` (hardest thing in CS is naming). This should be reducing memory consumption because it'll merely reference the port range instead of allocating into a slice all the possible addresses covered by the range.

## 2. Please link to the relevant issues.

Closes #2851 

## 3. Which documentation changes (if any) need to be made because of this PR?

None. I've already updated code comments.

## 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments explaining package types, values, functions, and non-obvious lines of code
- [x] I am willing to help maintain this change if there are issues with it later

### CODE REVIEW

**Comment by Mohammed90** [comment]
Something is panicking locally. Hold on.

**Comment by mholt** [comment]
I have pushed a fix for that "not a panic" bug, as well as a huge refactor for the admin endpoint code that took me like a week to do... sorry about the merge conflict.

**Comment by Mohammed90** [comment]
Messing with how admin bootstraps its config by employing the new type is too much of a hassle that could affect even the JSON structure. Adding private fields would be of low value because it'll only act as proxy between `ParseNetworkAddress` within the same func and not used elsewhere.

File: listeners.go [hunk 1]
```diff
@@ -262,43 +262,73 @@ var (
 	listenersMu sync.Mutex
 )
 
+const maxPortSpan = 65535
+
+type Listener struct {
+	Network  string
+	Host     string
+	FromPort uint
+	ToPort   uint
```
Comment (mholt) [inline listeners.go]: I might be a bit pendantic, but what if we called these `StartPort` and `EndPort` instead? (it's not really "going" from one port to another, even though yes in some sense it's a range or span, but I tend to think of From -> To when there is interaction between those things; these ports don't interact)

(Most editors should have a nice Rename Symbol option so that you don't have to replace all occurrences manually)

File: modules/caddyhttp/caddyhttp.go [hunk 2]
```diff
@@ -135,15 +135,16 @@ func (app *App) Validate() error {
...
-			netw, expanded, err := caddy.ParseNetworkAddress(addr)
+			listenAddr, err := caddy.ParseNetworkAddress(addr)
 			if err != nil {
 				return fmt.Errorf("invalid listener address '%s': %v", addr, err)
 			}
-			for _, a := range expanded {
-				if sn, ok := lnAddrs[netw+a]; ok {
-					return fmt.Errorf("server %s: listener address repeated: %s (already claimed by server '%s')", srvName, a, sn)
+			for i := listenAddr.FromPort; i <= listenAddr.ToPort; i++ {
+				addr := net.JoinHostPort(fmt.Sprintf("%s://%s", listenAddr.Network, listenAddr.Host), fmt.Sprintf("%d", i))
```
Comment (mholt) [inline modules/caddyhttp/caddyhttp.go]: There should be a method on the struct to do this for us.

(Also, this format is wrong -- these aren't URLs!)

Or, why not use `JoinNetworkAddress()`?

File: modules/caddyhttp/caddyhttp.go [hunk 3]
```diff
@@ -176,14 +177,15 @@ func (app *App) Start() error {
...
 		for _, lnAddr := range srv.Listen {
-			network, addrs, err := caddy.ParseNetworkAddress(lnAddr)
+			listenAddr, err := caddy.ParseNetworkAddress(lnAddr)
 			if err != nil {
 				return fmt.Errorf("%s: parsing listen address '%s': %v", srvName, lnAddr, err)
 			}
-			for _, addr := range addrs {
-				ln, err := caddy.Listen(network, addr)
+			for i := listenAddr.FromPort; i <= listenAddr.ToPort; i++ {
+				hostport := net.JoinHostPort(listenAddr.Host, fmt.Sprintf("%d", i))
```
Comment (mholt) [inline modules/caddyhttp/caddyhttp.go]: There should be a method to do this for us.

(Ideally, using this struct will not make our code more complex, i.e. it shouldn't make us do more work.)

File: modules/caddyhttp/server.go [hunk 4]
```diff
@@ -241,40 +241,38 @@ func (s *Server) enforcementHandler(w http.ResponseWriter, r *http.Request, next
...
+		if thisAddrs.Network != laddrs.Network {
 			continue
 		}
-		for _, a := range thisAddrs {
-			if a == addr {
-				return true
-			}
+
+		// If we have the same host on both sides, and the port of fullAddr falls within the port range of thisAddrs
+		if (thisAddrs.Host == laddrs.Host) && (laddrs.FromPort <= thisAddrs.ToPort && laddrs.FromPort >= thisAddrs.FromPort) {
```
Comment (mholt) [inline modules/caddyhttp/server.go]: This line's a bit long; split into two lines.

File: modules/caddyhttp/reverseproxy/hosts.go [hunk 5]
```diff
@@ -193,27 +192,20 @@ func (di DialInfo) String() string {
...
+			upstream.Dial, dial, addr.PortSpanSize())
 	}
 	return DialInfo{
 		Upstream: upstream,
-		Network:  netw,
-		Address:  addrs[0],
-		Host:     dialHost,
-		Port:     dialPort,
+		Network:  addr.Network,
+		Address:  net.JoinHostPort(addr.Host, fmt.Sprintf("%d", addr.FromPort)),
```
[the remark this answers is not in the document]
Comment (Mohammed90) [reply modules/caddyhttp/reverseproxy/hosts.go]: It's used in those 3 locations. If we drop it, we'd have to recreate it in each of these locations.

https://github.com/caddyserver/caddy/blob/54e458b756cf2cdb8adb750e822ead8e3a973441/modules/caddyhttp/reverseproxy/httptransport.go#L75-L91
https://github.com/caddyserver/caddy/blob/dccba71276796999f3e16a6560016dc5dd0a952a/modules/caddyhttp/reverseproxy/reverseproxy.go#L269

https://github.com/caddyserver/caddy/blob/dccba71276796999f3e16a6560016dc5dd0a952a/modules/caddyhttp/reverseproxy/reverseproxy.go#L542-L556

**Comment by Mohammed90** [comment]
Is more expected from me on this, or you just need the time to review it? Just wondering if I'm missing something

**Comment by mholt** [comment]
I'm working through a bunch of stuff, will get back to reviewing this soon 😅 Sorry for the delay!

(This is kind of a larger change so a single pass takes a while.)

**Comment by Mohammed90** [comment]
Okay, no worries, take your time 👌🏼 Just thought I could utilize the time if I missed something.
