### PR TITLE
httpcaddyfile: allow modules to customize listener wrappers

### LINKED ISSUE #3394: Question: How do I write a module and directive to wrap net.Listener
_Thank you so much for this project. I started playing with it over the weekend and decided to build custom modules and directives to simulate failures. It's made me excited to write code in my personal time all over again!_

**Background**

I want to build a suite of modules that plug in to Caddy and allow it to inject failures for the purpose of testing failure recovery. For example, I would deploy a Caddy reverse proxy in front of some API and add directives to delay the response or rate limit agressively.

**Question**

The current problem I'm facing is that I've written a module that implements `caddy.ListenerWrapper` and injects a long pause before accepting connections. I want to have it controlled by a directive like so `miasma_tarpit 10s`. I can't seem to understand how to use `httpcaddyfile.RegisterDirective` to register the directive. In particular, I'm not understanding what sort of []ConfigValue I should be returning. I'm not sure what value for `Class` I should pass. Can you help understand what I'm doing wrong?

**Code**

The module:

```go
package tarpit

import (
	"context"
	"fmt"
	"math/rand"
	"net"
	"time"

	"github.com/caddyserver/caddy/v2"
	"go.uber.org/zap"
)

func init() {
	caddy.RegisterModule(Tarpit{})
	httpcaddyfile.RegisterDirective("miasma_tarpit", parseCaddyfile)
}


type tarpitKey int

// Tarpit is a Caddy module that alters response times
type Tarpit struct {
	rootContext context.Context
	random      *rand.Rand
	logger      *zap.Logger

	// TODO
	Delay time.Duration `json:"delay,omitempty"`
}

var (
	_ caddy.Module          = (*Tarpit)(nil)
	_ caddy.Provisioner     = (*Tarpit)(nil)
	_ caddy.Validator       = (*Tarpit)(nil)
	_ caddy.ListenerWrapper = (*Tarpit)(nil)
)

// CaddyModule returns the Caddy module information.
func (Tarpit) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		ID:  "caddy.listeners.miasma_tarpit",
		New: func() caddy.Module { return new(Tarpit) },
	}
}

// Provision initializes the internal state of the Tarpit module
func (t *Tarpit) Provision(ctx caddy.Context) error {
	fmt.Println("PROVISION")
	t.rootContext = context.WithValue(ctx, tarpitKey(0), nil)
	t.logger = ctx.Logger(t)

	return nil
}

// Validate ensures the configuration for the Tarpit module is valid
func (t *Tarpit) Validate() error {
	fmt.Println("VALIDATE")
	if t.logger == nil {
		return fmt.Errorf("logger cannot be nil")
	}

	if t.Delay <= 0 {
		return fmt.Errorf("tarpit delay must be great than zero: %v", t.Delay)
	}

	return nil
}

func (t *Tarpit) WrapListener(listener net.Listener) net.Listener {
	return &tarpitListener{
		rootContext: t.rootContext,
		underlying:  listener,
		delay:       t.Delay,
	}
}

type tarpitListener struct {
	rootContext context.Context
	underlying  net.Listener
	delay       time.Duration
}

func (l *tarpitListener) Accept() (net.Conn, error) {
	select {
	case <-l.rootContext.Done():
		return nil, context.Canceled
	case <-time.After(l.delay):
		return l.underlying.Accept()
	}
}

func (l *tarpitListener) Close() error {
	return l.underlying.Close()
}

func (l *tarpitListener) Addr() net.Addr {
	return l.underlying.Addr()
}

func parseCaddyfile(h httpcaddyfile.Helper) ([]httpcaddyfile.ConfigValue, error) {
	var tarpit Tarpit

	if !h.Next() {
		return nil, h.ArgErr()
	}

	_, err := h.ExtractMatcherSet()
	if err != nil {
		return nil, err
	}

	if !h.Next() {
		return nil, h.ArgErr()
	}

	args := h.RemainingArgs()

	fmt.Println(args)

	if len(args) != 1 {
		return nil, h.ArgErr()
	}

	delay, err := time.ParseDuration(args[0])
	if err != nil {
		return nil, err
	}

	tarpit.Delay = delay

	// what do I return???
}
```

### PR DESCRIPTION
**Pull request by disintegrator**
This changes grants modules the ability to customize the listener wrapppers by introducing a new server block pile called listener_wrappers.
For example directives can now return `ConfigValue`s like so:

```go
package custom

type CustomModule struct {}

func init() {
	caddy.RegisterModule(CustomModule{})
	httpcaddyfile.RegisterDirective("custom_listener", parseCaddyfile)
}

var (
	_ caddy.Module          = (*CustomModule)(nil)
	_ caddy.ListenerWrapper = (*CustomModule)(nil)
)

func (c *CustomModule) WrapListener(listener net.Listener) net.Listener {
	// omitted to keep the example short but you probably want to wrap this
	// incoming listener with your own customised one
	return listener
}

func parseCaddyfile(h httpcaddyfile.Helper) ([]httpcaddyfile.ConfigValue, error) {
	var mod CustomModule

	// initialize your custom module from by parsing the directive

	return []ConfigValue{{
		Class: "listener_wrapper",
		Value: &mod,
	}}
}
```

Closes #3394

### CODE REVIEW

**Comment by disintegrator** [comment]
@mholt here's my attempt at allowing modules to add listener wrappers. I'm gonna to carry on with writing tests tomorrow - bit late in the UK :)

File: caddyconfig/httpcaddyfile/httptype.go [hunk 1]
```diff
@@ -425,6 +425,24 @@ func (st *ServerType) serversFromPairings(
 					(addr.Port == httpsPort || (addr.Port != httpPort && addr.Host != ""))
 			}
 
+			// Look for any config values that provide listener wrappers on the
+			// server block
+			for _, listenerConfig := range sblock.pile["listener_wrapper"] {
+				listenerWrapper, ok := listenerConfig.Value.(caddy.ListenerWrapper)
+
+				if !ok {
```
Comment (mholt) [inline caddyconfig/httpcaddyfile/httptype.go:433]:
```suggestion
				listenerWrapper, ok := listenerConfig.Value.(caddy.ListenerWrapper)
				if !ok {
```

File: caddyconfig/httpcaddyfile/httptype.go [hunk 2]
```diff
@@ -425,6 +425,24 @@ func (st *ServerType) serversFromPairings(
...
+					return nil, fmt.Errorf("config for a listener wrapper did not provide a value that implements caddy.ListenerWrapper")
+				}
+
+				jsonListenerWrapper := caddyconfig.JSONModuleObject(
```
Comment (mholt) [inline caddyconfig/httpcaddyfile/httptype.go:437]:
```suggestion
				}
				jsonListenerWrapper := caddyconfig.JSONModuleObject(
```

File: caddyconfig/httpcaddyfile/httptype.go [hunk 3]
```diff
@@ -425,6 +425,24 @@ func (st *ServerType) serversFromPairings(
...
+					listenerWrapper,
+					"wrapper",
+					listenerWrapper.(caddy.Module).CaddyModule().ID.Name(),
+					warnings)
+
+				srv.ListenerWrappersRaw = append(srv.ListenerWrappersRaw, jsonListenerWrapper)
```
Comment (mholt) [inline caddyconfig/httpcaddyfile/httptype.go:443]:
```suggestion
					warnings)
				srv.ListenerWrappersRaw = append(srv.ListenerWrappersRaw, jsonListenerWrapper)
```

File: caddyconfig/httpcaddyfile/httptype.go [hunk 4]
```diff
@@ -425,6 +425,24 @@ func (st *ServerType) serversFromPairings(
 					(addr.Port == httpsPort || (addr.Port != httpPort && addr.Host != ""))
 			}
 
+			// Look for any config values that provide listener wrappers on the
+			// server block
```
Comment (mholt) [inline caddyconfig/httpcaddyfile/httptype.go:429]:
```suggestion
			// Look for any config values that provide listener wrappers on the server block
```

**Comment by mholt** [comment]
@disintegrator Anything else on this? Any thoughts ^ ?

**Comment by mholt** [comment]
@disintegrator Do you still need this? I don't want to add code to the core that is unneeded...

**Comment by disintegrator** [comment]
All good for now @mholt. I'll close this PR until I'm able to resume the work.

**Comment by disintegrator** [comment]
sorry for my absence :/

**Comment by mholt** [comment]
No worries -- and no need to close this, in fact I'm going to reopen it if that's OK.

To clarify: I just wanted to make sure this PR does indeed do what you need. If so, I'll merge it -- if any further review is required though, I can hold off.
