### PR TITLE
autohttps: deterministic logic and strict bind checking on Linux

### LINKED ISSUE #5660: Automatic HTTPS redirects inconsistent in combination with bindings
What I want to achieve: For Caddy to serve some public sites to the internet over HTTPS with an automatic redirect from HTTP, and some private sites to a [Tailscale][tailscale] ([Headscale][headscale]) network over plain HTTP.

[tailscale]: https://tailscale.com/
[headscale]: https://github.com/juanfont/headscale/

I first tried to set it up like the following. (I've simplified the configuration a lot for local testing, but the problem is the same.)

```
# Public site
test.example {
	bind 127.0.0.1
	tls internal
	respond "Hello"
}

# Private site
http://test2.example {
	bind 100.64.0.6
	respond "World"
}
```

The result is Caddy listening on port 80 on 100.64.0.6, and port 443 on 127.0.0.1. The listener on port 80 *will* redirect to `https://test.example`.

<details>
<summary>Expand for test commands</summary>

```
# Not listening to port 80 on 127.0.0.1
$ curl --insecure --include --connect-to test.example:80:127.0.0.1:80 http://test.example/
curl: (7) Failed to connect to 127.0.0.1 port 80 after 0 ms: Couldn't connect to server

# Listening and redirecting on 100.64.0.6
$ curl --insecure --include --connect-to test.example:80:100.64.0.6:80 http://test.example/
HTTP/1.1 308 Permanent Redirect
...
```
</details>

This feels like a bug, but it can be explained based on the warning in the [documentation for `default_bind`][warning-default-bind]. The solution offered there (Also discussed in #5309) is to add an `http://` site, like this:

[warning-default-bind]: https://caddyserver.com/docs/caddyfile/options#default-bind

```
# Public site
test.example {
	bind 127.0.0.1
	tls internal
	respond "Hello"
}

# Private site
http://test2.example {
	bind 100.64.0.6
	respond "World"
}

# Fix
http:// {
	bind 127.0.0.1
	respond "Fix"
}
```

Whether this solves the problem here is unpredictable every time Caddy gets restarted. The listener for the automatic redirects appears to be selected at random. (`caddy adapt` consistently returns the same JSON for this Caddyfile, so the inconsistency is not in the adaptation.)

<details>
<summary>Expand for test commands</summary>

```
# Start Caddy with the above Caddyfile

# 200 OK on 127.0.0.1
$ curl --insecure --include --connect-to test.example:80:127.0.0.1:80 http://test.example/
HTTP/1.1 200 OK
...
Fix

# 308 Permanent Redirect on 100.64.0.6
$ curl --insecure --include --connect-to test.example:80:100.64.0.6:80 http://test.example/
HTTP/1.1 308 Permanent Redirect
...

# Restart Caddy a few times without changing the Caddyfile

# 308 Permanent Redirect on 127.0.0.1
$ curl --insecure --include --connect-to test.example:80:127.0.0.1:80 http://test.example/
HTTP/1.1 308 Permanent Redirect
...

# 200 OK on 100.64.0.6 (but unrelated to the new catch-all http:// site)
$ curl --insecure --include --connect-to test.example:80:100.64.0.6:80 http://test.example/
HTTP/1.1 200 OK
...
```
</details>

My first attempted configuration did not specify `bind` for the public sites. I thought the warning about inconsistent binding in the [documentation for `bind`][warning-bind] could apply, but as you can see above specifying a non-overlapping binding does not fix it.

[warning-bind]: https://caddyserver.com/docs/caddyfile/directives/bind#bind

### PR DESCRIPTION
**Pull request by pauloappbr**
## Description 
This PR addresses an issue where Automatic HTTPS redirects would intermittently bind to the wrong listener (or fail to bind entirely) when using multiple specific loopback addresses on Linux (e.g., binding one site to 127.0.0.2 and another to 127.0.0.3).

The issue was caused by a combination of two factors creating a race condition:

Non-deterministic Map Iteration (autohttps.go): The iteration over app.Servers and redirDomains was relying on Go's default map randomization. Depending on the iteration order, Caddy would sometimes correctly create a new server for the redirect, but other times it would incorrectly match the redirect to an existing server that shared the same port but a different IP.

Loose Linux Bind Logic (server.go): The hasListenerAddress function contained logic specifically for Linux that treated different specific IPs (e.g., 127.0.0.2 vs 127.0.0.3) as identical/overlapping to avoid wildcard conflicts. This caused autohttps to assume an existing server could handle the redirect for a different IP simply because they shared the same port, leading to bind: connection refused or traffic hijacking.

## Changes

modules/caddyhttp/autohttps.go:

Added slices.Sort to srvNames loop to ensure servers are processed in a deterministic order.

Added slices.Sort to redirServerAddrs loop to ensure redirect injections happen consistently.

This eliminates the "random" nature of the bug.

modules/caddyhttp/server.go:

Updated hasListenerAddress to improve matching logic on Linux.

It now correctly distinguishes between two different specific IPs (allowing multihoming).

It maintains the protection against Specific-vs-Wildcard conflicts (e.g., binding 127.0.0.1 when 0.0.0.0 is already bound still returns true/conflict).

## Testing & Verification

I created a reproduction Go script that spawns Caddy 50 times with a config using aliases 127.0.0.2 and 127.0.0.3 (simulating the issue environment).

Before fix: The setup failed randomly (~50% of the time) with dial tcp 127.0.0.2:80: connect: connection refused because the redirect was injected into the wrong server listener.

After fix: 0 failures in 50 iterations. The redirect server is correctly created every time.

I also ran go test -v ./modules/caddyhttp/... to ensure no regressions in existing binding logic.

## Assistance Disclosure

I used Gemini to help analyze the race condition, generate the reproduction script, and draft the fix. I verified the solution works using the reproduction script and ran the existing tests to ensure no regressions.

### CODE REVIEW

File: modules/caddyhttp/server.go [hunk 1]
```diff
@@ -541,30 +541,17 @@ func (s *Server) hasListenerAddress(fullAddr string) bool {
...
-		//
-		// This is very easy to reproduce by creating an HTTP server
-		// that listens to both addresses or just one with a host
-		// interface; or for a more confusing reproduction, try
-		// listening on "127.0.0.1:80" and ":443" and you'll see
-		// the error, if you take away the GOOS condition below.
-		//
-		// So, an address is equivalent if the port is in the port
-		// range, and if not on Linux, the host is the same... sigh.
-		if (runtime.GOOS == "linux" || thisAddrs.Host == laddrs.Host) &&
```
Comment (francislavoie) [inline modules/caddyhttp/server.go:567]: I think this comment had good information about context for this that sorta gets lost with the new comment. I think that should be readjusted to keep as much of the relevant detail about reproduce steps and such

**Comment by francislavoie** [comment]
Thanks! The deterministic looping in autohttps totally make sense, that looks correct. The server change I find a bit harder to wrap my head around (tricky boolean logic), but it makes sense to me as described.

File: modules/caddyhttp/server.go (hunk 1 above)
Comment (pauloappbr) [reply modules/caddyhttp/server.go:567]: Thanks for the review, @francislavoie! You are right, that context is valuable.

I've just pushed a commit that restores the original explanation about the Linux wildcard behavior and the NodeJS issue link, while appending a note clarifying that specific-to-specific binding is actually valid (which is what this logic now enables).
