### PR TITLE
reverseproxy: Fix dynamic upstreams ip version

### LINKED ISSUE #6442: can't disable IPv4/IPv6 for dynamic reverse proxy from Caddyfile
As per the forum discussion at https://caddy.community/t/reverse-proxy-to-dynamic-ipv4-only/24773/3 , I found it's not possible to disable IPv4 or IPv6 in a `reverse_proxy` `dynamic a` block from the Caddyfile.

If I use
```
:9000 {
	reverse_proxy {
		dynamic a potoroo 8123 {
			versions ipv4
		}
	}
}
```

then I get a caddy.json which has `"versions":{"ipv4":true}}`, but Caddy still uses IPv6 if available. 

If I explicitly add `"ipv6":"false"` then it works, but this can't be set from the Caddyfile (that I'm aware of).

### PR DESCRIPTION
**Pull request by armadi1809**
Closes #6442

### CODE REVIEW

File: modules/caddyhttp/reverseproxy/upstreams.go [hunk 1]
```diff
@@ -313,8 +313,8 @@ func (au *AUpstreams) Provision(ctx caddy.Context) error {
 func (au AUpstreams) GetUpstreams(r *http.Request) ([]*Upstream, error) {
 	repl := r.Context().Value(caddy.ReplacerCtxKey).(*caddy.Replacer)
 
-	resolveIpv4 := au.Versions == nil || au.Versions.IPv4 == nil || *au.Versions.IPv4
-	resolveIpv6 := au.Versions == nil || au.Versions.IPv6 == nil || *au.Versions.IPv6
+	resolveIpv4 := au.Versions == nil || (au.Versions.IPv4 == nil && au.Versions.IPv6 == nil) || (au.Versions.IPv6 != nil && *au.Versions.IPv4)
```
Comment (francislavoie) [inline modules/caddyhttp/reverseproxy/upstreams.go:316]:
```suggestion
	resolveIpv4 := au.Versions == nil || (au.Versions.IPv4 == nil && au.Versions.IPv6 == nil) || (au.Versions.IPv4 != nil && *au.Versions.IPv4)
```

**Comment by francislavoie** [comment]
I think a test would be useful for this if you have time to look into that 🤔 we could refactor this logic to a separate function to return a tuple of booleans so it can be tested as a unit.

**Comment by armadi1809** [comment]
@francislavoie I just refactored the logic determining the ip version into its own function and added a test covering all possible combinations of `au.Versions`.

File: modules/caddyhttp/reverseproxy/upstreams.go [hunk 2]
```diff
@@ -397,6 +386,19 @@ func (au AUpstreams) GetUpstreams(r *http.Request) ([]*Upstream, error) {
 
 func (au AUpstreams) String() string { return net.JoinHostPort(au.Name, au.Port) }
 
+func resolveIpVersion(versions *IPVersions) string {
```
Comment (francislavoie) [inline modules/caddyhttp/reverseproxy/upstreams.go:389]: I think we should move this function to just below the IPVersions type (higher in this file) since it's tightly related.

**Review by francislavoie — APPROVED** [review]
Thanks! Looks great 😊

File: modules/caddyhttp/reverseproxy/upstreams.go (hunk 2 above)
Comment (armadi1809) [reply modules/caddyhttp/reverseproxy/upstreams.go]: Done.

**Comment by calvinbrewer** [comment]
Still running into this issue, but it looks like a release hasn't been cut since June 2nd. What is the release cadence for deploying these new changes? Cheers!
