### PR TITLE
cmd: Add `--envfile` flag to `validate` command

### LINKED ISSUE #5346: caddy validate --envfile
Is there a way to use caddy validate CLI and pass it --envfile? I get this error whenever I try to run it…

```
Error: loading tls app module: provision tls: provisioning automation policy 0: loading TLS automation management module: position 0: loading module 'acme': provision tls.issuance.acme: expanding email address '{env.EMAIL}': evaluated placeholder {env.EMAIL} is empty
```

### PR DESCRIPTION
**Pull request by amis-shokoohi**
Fixes  #5346

### CODE REVIEW

File: cmd/commands.go [hunk 1]
```diff
@@ -297,6 +297,7 @@ provisioning stages.`,
 			fs := flag.NewFlagSet("validate", flag.ExitOnError)
 			fs.String("config", "", "Input configuration file")
 			fs.String("adapter", "", "Name of config adapter")
+			fs.String("envfile", "", "Environment file to load")
```
Comment (francislavoie) [inline cmd/commands.go:300]: Please add `--envfile` documentation to the `Long` doc as well. See the `run` command for an example of how it should look.

**Review by francislavoie — APPROVED** [review]
Great, thank you! Looks good to me :+1:
