### PR TITLE
reverse_proxy: Fix random_choose lb_policy

### LINKED ISSUE #3810: lb_policy random_choose may failed when some upsteam are down
## Caddy version:
```
./caddy_linux_amd64 version
v2.2.1 h1:Q62GWHMtztnvyRU+KPOpw6fNfeCD3SkwH7SfT1Tgt2c=
```

### Caddyfile:
```
{
 debug
 admin localhost:2010
 auto_https disable_redirects
}

http://localhost:8443 {
    respond "ok"
}
http://localhost:8444 {
    respond "ok"
}

http://localhost:8442 {
    reverse_proxy /* {
        to http://localhost:8445 http://localhost:8443 http://localhost:8444
        lb_policy random_choose 2
        health_interval 1s
        health_path /
    }
}
```

### Run caddy:

```
./caddy_linux_amd64 run --config Caddyfile
```

### Test:

```
curl  -v http://localhost:8442
* About to connect() to localhost port 8442 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8442 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8442
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

### Log ouput:
```
2020/10/19 10:36:50.774 INFO    http.handlers.reverse_proxy.health_checker.active       HTTP request failed     {"host": "localhost:8445", "error": "Get \"http://localhost:8445/\": dial tcp [::1]:8445: connect: connection refused"}
2020/10/19 10:36:51.105 DEBUG   http.stdlib     http: panic serving [::1]:45622: runtime error: invalid memory address or nil pointer dereference
goroutine 137 [running]:
net/http.(*conn).serve.func1(0xc00047cfa0)
        net/http/server.go:1800 +0x139
panic(0x1515b20, 0x25de6d0)
        runtime/panic.go:975 +0x3e3
github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.leastRequests(0xc0001c6190, 0x2, 0x2, 0xc0001c6190)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/reverseproxy/selectionpolicies.go:402 +0x8b
github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.RandomChoiceSelection.Select(0x2, 0xc0008560a0, 0x3, 0x4, 0xc0001ccf00, 0x75c2b21f5ca)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/reverseproxy/selectionpolicies.go:152 +0x11e
github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).ServeHTTP(0xc00054e1e0, 0x7f4f9fa650e8, 0xc0008e50e0, 0xc0001ccf00, 0x1a18d40, 0x17d2d50, 0x0, 0x0)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/reverseproxy/reverseproxy.go:371 +0x3d4
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc0008562e0, 0x7f4f9fa650e8, 0xc0008e5020, 0xc0001ccf00, 0x1a18d40, 0x17d2d50, 0x0, 0x0)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/metrics.go:133 +0x537
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x7f4f9fa650e8, 0xc0008e5020, 0xc0001ccf00, 0xc0005128e0, 0xc0008562e0)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/routes.go:259 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0005128e0, 0x7f4f9fa650e8, 0xc0008e5020, 0xc0001ccf00, 0x1, 0x0)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/caddyhttp.go:58 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x7f4f9fa650e8, 0xc0008e5020, 0xc0001ccf00, 0x1, 0x1)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/routes.go:231 +0x121
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0005128c0, 0x7f4f9fa650e8, 0xc0008e5020, 0xc0001ccf00, 0x17d2d50, 0x1a18d40)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/caddyhttp.go:58 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc000821b80, 0x7f4f9fa650e8, 0xc0008e5020, 0xc0001ccf00, 0x1a18d40, 0x17d2d50, 0xffffffffffffff01, 0x1)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/subroute.go:74 +0x8a
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc000856340, 0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0x1a18d40, 0x17d2d50, 0x0, 0x0)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/metrics.go:133 +0x537
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0xc0005128a0, 0xc000856340)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/routes.go:259 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0005128a0, 0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0x1, 0x1)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/caddyhttp.go:58 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0xc00090d498, 0x40c976)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/routes.go:231 +0x121
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000856360, 0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0x7, 0x2)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/caddyhttp.go:58 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0xc0008030e0, 0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0x1a18d40, 0xc000856360, 0x75c2b2190c6, 0x641e4ab)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/server.go:287 +0x9b
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1(0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0xc00641e4ab, 0x75c2b2190c6)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/server.go:263 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000856380, 0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0xc000251100, 0xc0001ccf00)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/caddyhttp.go:58 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc0008030e0, 0x1a32820, 0xc0008d0620, 0xc0001ccf00)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/server.go:204 +0x4b3
net/http.serverHandler.ServeHTTP(0xc0006ec000, 0x1a32820, 0xc0008d0620, 0xc0001ccd00)
        net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc00047cfa0, 0x1a390e0, 0xc0005eb380)
        net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        net/http/server.go:2962 +0x35c
2020/10/19 10:36:51.769 INFO    http.handlers.reverse_proxy.health_checker.active       HTTP request failed     {"host": "localhost:8445", "error": "Get \"http://localhost:8445/\": dial tcp [::1]:8445: connect: connection refused"}
```

See Pull Request: https://github.com/caddyserver/caddy/pull/3811

### PR DESCRIPTION
**Pull request by d-masson**
fix #3810

### CODE REVIEW

File: modules/caddyhttp/reverseproxy/selectionpolicies.go [hunk 1]
```diff
@@ -397,13 +400,12 @@ func leastRequests(upstreams []*Upstream) *Upstream {
...
+	var bestReqs int = -1
 	for _, upstream := range upstreams {
 		reqs := upstream.NumRequests()
-		if reqs == 0 {
-			return upstream
-		}
-		if reqs <= bestReqs {
+		// If bestReqs was just initialized to -1
+		// we need to append upstream also
+		if reqs <= bestReqs || bestReqs == -1 {
```
Comment (mholt) [inline modules/caddyhttp/reverseproxy/selectionpolicies.go:408]: I don't really understand this; if an upstream has 0 requests, it is already the least it can be, therefore we can use it.

File: modules/caddyhttp/reverseproxy/selectionpolicies.go [hunk 2]
```diff
@@ -139,14 +139,17 @@ func (r RandomChoiceSelection) Select(pool UpstreamPool, _ *http.Request) *Upstr
 	if k > len(pool) {
 		k = len(pool)
 	}
-	choices := make([]*Upstream, k)
+	// Slice of length 0 and capacity k (if we use an array and have some unavailable
+	// upstream, we could have some empty element which may lead
+	// to an index out of range runtime error)
```
Comment (mholt) [inline modules/caddyhttp/reverseproxy/selectionpolicies.go:144]: I think this logic is pretty self-explanatory (actually the comment made me a little more confused). After attempting to solve the problem independently myself, I came to the same code, so I think we can just remove the comment.

```suggestion
```

**Review by mholt — CHANGES_REQUESTED** [review]
Thanks for the report and the quick fix! I have a few questions/nits before we merge this.

File: modules/caddyhttp/reverseproxy/selectionpolicies.go (hunk 2 above)
Comment (d-masson) [reply modules/caddyhttp/reverseproxy/selectionpolicies.go:144]: Ok, I'll do that

File: modules/caddyhttp/reverseproxy/selectionpolicies.go (hunk 1 above)
Comment (d-masson) [reply modules/caddyhttp/reverseproxy/selectionpolicies.go:408]: Actually, there is 2 problems:

- Firstly, with the old implementation of function leastRequests, there is an issue when all upstream server numRequest is at least 1: as bestReqs is initialized to 0, this condition (`reqs <= bestReqs`) can never be true, so the function return nil and we have a 502 http response code
(see [here](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/selectionpolicies.go#L187) where is the right condition for the same problem)

It is easily reproducible with the unit test I add (TestLeastRequests) or by doing some concurrent http request.




- Secondly, -by replacing `choices[j] = upstream` by `choices = append(choices, upstream)`, I observed that there were no more random, and it was always the first upsteam server that was chosen when the numRequest was 0.
Removing the `if reqs == 0 { return upsteam }` was a way to solve that.

Now, I realize that using append was a bad idea: the pool with random host will always contains the first upstreams and the pool size will not always match the configured size.


So I will rollback this change, and instead I'm gonna bypass nil upstream on leastRequests function

**Review by mholt — APPROVED** [review]
Great, this looks good. Thanks so much for your contribution! Appreciate the fix!
