### PR TITLE
cmd: Pass configFile, not configFlag, for reload command

### LINKED ISSUE #7528: Caddy 2.11 HTTP 403 error via docker exec caddy reload
# Issue Details

Per https://caddy.community/t/caddy-2-11-http-403-error-via-docker-exec-caddy-reload/33526; Caddy's `origin` host header checking on the Admin interface may be affecting how `caddy reload` functions in a container-based Caddy deployment.

We utilise caddy running as a docker image as an 'ingress service router' for our platform. As part of the update process, our CI/CD pipeline (Gitlab CI/CD) connects to the docker host, refreshes the project and then will run ‘caddy reload’ to ensure up to date config is loaded.
This is is done via:

`docker exec -w /etc/caddy ingress-router-caddy-1 caddy reload`

This has worked without issue on Caddy v2.10. After updating the image to Caddy v2.11.1 this morning, we now see the following problem:

```
$ docker exec -w /etc/caddy ingress-router-caddy-1 caddy reload
{"level":"info","ts":1772070489.923556,"msg":"using adjacent Caddyfile"}
{"level":"warn","ts":1772070489.945869,"msg":"The nested 'metrics' option inside `servers` is deprecated and will be removed in the next major version. Use the global 'metrics' option instead."}
{"level":"info","ts":1772070489.9707046,"msg":"adapted config to JSON","adapter":"caddyfile"}
Error: sending configuration to instance: caddy responded with error: HTTP 403: {"error":"client is not allowed to access from origin 'http://localhost:2019'"}
```

This occurs both manually and in the Gitlab CI/CD pipeline.

## Caddy version:

```
$ docker exec -w /etc/caddy ingress-router-caddy-1 caddy version
v2.11.1 h1:C7sQpsFOC5CH+31KqJc7EoOf8mXrOEkFyYd6GpIqm/s=
```

### PR DESCRIPTION
**Pull request by mholt**
This *should* fix #7528.

I believe we don't need configFlag after we pass it into `LoadConfig()`, which uses it to load the config, and we get the resulting `configFile` used from that function.

Without this patch, `caddy reload` was definitely not using the adjacent Caddyfile unless I did `caddy reload --config Caddyfile`, which shouldn't be necessary.

## Assistance Disclosure

No AI was used. Just my dumb self

### CODE REVIEW

File: cmd/commandfuncs.go [hunk 1]
```diff
@@ -757,6 +757,7 @@ func handleEnvFileFlag(fl Flags) error {
 // need to interact with a running instance of Caddy via the admin API.
 func AdminAPIRequest(adminAddr, method, uri string, headers http.Header, body io.Reader) (*http.Response, error) {
 	parsedAddr, err := caddy.ParseNetworkAddress(adminAddr)
+	log.Println("ADMIN ADDR:", adminAddr, parsedAddr)
```
Comment (francislavoie) [inline cmd/commandfuncs.go]:
```suggestion
```

File: cmd/commandfuncs.go [hunk 2]
```diff
@@ -372,7 +372,7 @@ func cmdReload(fl Flags) (int, error) {
 		return caddy.ExitCodeFailedStartup, fmt.Errorf("no config file to load")
 	}
 
-	adminAddr, err := DetermineAdminAPIAddress(addressFlag, config, configFlag, configAdapterFlag)
+	adminAddr, err := DetermineAdminAPIAddress(addressFlag, config, configFile, configAdapterFlag)
```
Comment (francislavoie) [inline cmd/commandfuncs.go:375]: 🫠 well that's an embarassing mistake

**Review by francislavoie — APPROVED** [review]

File: cmd/commandfuncs.go (hunk 2 above)
Comment (mholt) [reply cmd/commandfuncs.go:375]: I've done worse. Way worse :rofl:

File: cmd/commandfuncs.go (hunk 1 above)
Comment (mholt) [reply cmd/commandfuncs.go]: How'd that get in there :laughing:
