### PR TITLE
acme_server: fix reload of acme database

### LINKED ISSUE #3865: acme_server: error on reload
I started with this config:

```json
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":80"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "localhost"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "acme_server"
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

To which I only added logging:

```json
{
  "logging": {
    "logs": {
      "log0": {
        "writer": {
          "output": "stderr"
        },
        "encoder": {
          "format": "json"
        }
      }
    }
  },
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "logs": {
            "logger_names": {
              "localhost": "log0"
            }
          },
          "listen": [
            ":80"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "localhost"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "acme_server"
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

Ran `caddy reload --config caddy.json` and got the error:

```
ERROR	admin.api	request error	{"error": "loading config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'acme_server': provision http.handlers.acme_server: initializing certificate authority: Error opening database of Type badger with source /Users/mohammed/Library/Application Support/Caddy/acme_server/db: error opening Badger database: Cannot acquire directory lock on \"/Users/mohammed/Library/Application Support/Caddy/acme_server/db\".  Another process is using this Badger database.: resource temporarily unavailable", "status_code": 400}

reload: sending configuration to instance: caddy responded with error: HTTP 400: {"error":"loading config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'acme_server': provision http.handlers.acme_server: initializing certificate authority: Error opening database of Type badger with source /Users/mohammed/Library/Application Support/Caddy/acme_server/db: error opening Badger database: Cannot acquire directory lock on \"/Users/mohammed/Library/Application Support/Caddy/acme_server/db\".  Another process is using this Badger database.: resource temporarily unavailable"}

2020/11/13 21:22:08.725	INFO	admin	stopped previous server
```

Note the `stopped previous server`. I haven't checked whether the acme endpoint still works.

### PR DESCRIPTION
**Pull request by ViViDboarder**
Now using a UsagePool to manage database instances.

Verified with the following `Caddyfile`.

Verifying graceful change by toggling debug on and off and graceful destruction by toggling `acme_server` and `respond` directives.

```
{
    local_certs
    debug
}

acme.localhost {
    acme_server
    # respond "ok"
}
```

One thing to note, now that the database paths are not wholly predictable, this branch no longer deletes old db directories.

Fixes #3865

### CODE REVIEW

**Comment by ViViDboarder** [comment]
Eventually this should fix #3865

**Comment by ViViDboarder** [comment]
@mholt this is based on the branch for my other change. Either we can merge that one first, or just merge this one since it includes both changes.

File: modules/caddypki/acmeserver/acmeserver.go [hunk 1]
```diff
@@ -160,11 +158,64 @@ func (ash Handler) ServeHTTP(w http.ResponseWriter, r *http.Request, next caddyh
...
+func (ash Handler) getDatabaseKey() string {
+	return ash.CA
+}
+
+// Cleanup implements caddy.CleanerUpper and closes any idle databases.
+func (ash Handler) Cleanup() error {
+	key := ash.getDatabaseKey()
+	deleted, err := databasePool.Delete(key)
+	if deleted {
+		ash.logger.Debug("unloading unused database", zap.String("caID", key))
```
Comment (mholt) [inline modules/caddypki/acmeserver/acmeserver.go:170]:
```suggestion
		ash.logger.Debug("unloading unused database", zap.String("db_key", key))
```

(We don't know that it's the CA ID since that is abstracted away into `getDatabaseKey()`)

File: modules/caddypki/acmeserver/acmeserver.go [hunk 2]
```diff
@@ -160,11 +158,64 @@ func (ash Handler) ServeHTTP(w http.ResponseWriter, r *http.Request, next caddyh
...
+	}
+	if err != nil {
+		ash.logger.Error("closing closing database", zap.String("caID", key), zap.Error(err))
```
Comment (mholt) [inline modules/caddypki/acmeserver/acmeserver.go:173]:
```suggestion
		ash.logger.Error("closing CA database", zap.String("db_key", key), zap.Error(err))
```

File: modules/caddypki/acmeserver/acmeserver.go [hunk 3]
```diff
@@ -160,11 +158,64 @@ func (ash Handler) ServeHTTP(w http.ResponseWriter, r *http.Request, next caddyh
...
+		dbConfig := &db.Config{
+			Type:       "bbolt",
+			DataSource: dbPath,
+		}
+		database, err := db.New(dbConfig)
+		return databaseCloser{&database}, err
+	})
+
+	if loaded {
+		ash.logger.Debug("Loaded preexisting CA DB", zap.String("caID", key))
```
Comment (mholt) [inline modules/caddypki/acmeserver/acmeserver.go:198]:
```suggestion
		ash.logger.Debug("loaded preexisting CA database", zap.String("db_key", key))
```

File: modules/caddypki/acmeserver/acmeserver.go [hunk 4]
```diff
@@ -160,11 +158,64 @@ func (ash Handler) ServeHTTP(w http.ResponseWriter, r *http.Request, next caddyh
 	return next.ServeHTTP(w, r)
 }
 
+func (ash Handler) getDatabaseKey() string {
+	return ash.CA
```
Comment (mholt) [inline modules/caddypki/acmeserver/acmeserver.go:162]: Note that the CA name may not be safe for use as a filename. In CertMagic we handle this by having a sanitizing function, e.g.:

https://github.com/caddyserver/certmagic/blob/81657a23377cad89ed4c08d3741b40b3cda055c5/storage.go#L190-L209

Ours doesn't have to be that elaborate, though. Could be a simple regex probably.

**Review by mholt — CHANGES_REQUESTED** [review]
This is definitely a much better approach. Thank you for working on it!

I have just a few comments, see what you think.

**Comment by ViViDboarder** [comment]
Thanks for the suggestions. I made sure the wording was consistent in the logs this time too.

File: modules/caddypki/acmeserver/acmeserver.go [hunk 5]
```diff
@@ -160,11 +158,68 @@ func (ash Handler) ServeHTTP(w http.ResponseWriter, r *http.Request, next caddyh
 	return next.ServeHTTP(w, r)
 }
 
+func (ash Handler) getDatabaseKey() string {
+	key := ash.CA
+	key = strings.ToLower(key)
+	key = strings.TrimSpace(key)
+	cleaner := regexp.MustCompile(`[^\w.-_]`)
```
Comment (mholt) [inline modules/caddypki/acmeserver/acmeserver.go:165]: Could move this into a package-level variable like `var acmeDBKeyCleaner = ...` or something, then we don't have to recompile it each time. Not a big deal though, I don't think this is a hot code path.

**Review by mholt — COMMENTED** [review]
I think this is looking good -- just needs to resolve the merge conflict I introduced when I merged the other PR :man_facepalming:

File: modules/caddypki/acmeserver/acmeserver.go (hunk 5 above)
Comment (ViViDboarder) [reply modules/caddypki/acmeserver/acmeserver.go:165]: Ah. That makes sense. I can probably push that quickly, but if you're resolving a merge conflict, I don't want to make it difficult.

Comment (mholt) [reply modules/caddypki/acmeserver/acmeserver.go:165]: I haven't started with it, something else came up. If you get to it before I do, that  works too!

Comment (ViViDboarder) [reply modules/caddypki/acmeserver/acmeserver.go:165]: You want me to rebase and push as well to get rid of the conflict?

Comment (mholt) [reply modules/caddypki/acmeserver/acmeserver.go]: Sure! We can merge this in then, after the tests finish.

Comment (ViViDboarder) [reply modules/caddypki/acmeserver/acmeserver.go]: I've rebased and can force push to this PR if you'd like, but if you've already fixed the conflict on your end, I'll trash it.

Comment (ViViDboarder) [reply modules/caddypki/acmeserver/acmeserver.go]: Pushed.

**Review by mholt — APPROVED** [review]
Great, thanks! This looks good. I'll merge it now. Really appreciate your help.

I'm also sending an invite to give you collaborator status on the repository, so in the future you can review PRs or make changes in a branch instead of a fork, etc. Feel free to accept if you'd like, we're always looking for skilled maintainers!
